'use strict';

/**
 * brandResolver.js
 *
 * Resolves the effective brand for a given userId by reading:
 *   - agencyBrandOverrides/{uid}  — user-configurable fields (logoUrl, accentColor, etc.)
 *   - agencyEntitlements/{uid}    — server-controlled capabilities (planTier, canUseCustomLogo, etc.)
 *
 * Returns a normalized `resolvedBrand` contract consumed by all renderers.
 * NEVER throws — always falls back to PATHSYNCH_DEFAULT_BRAND.
 *
 * Authority and branding are reread per request; no retained result cache.
 */

const admin = require('firebase-admin');

// ---------------------------------------------------------------------------
// Default brand (mode: 'pathsynch')
// ---------------------------------------------------------------------------
const PATHSYNCH_DEFAULT_BRAND = Object.freeze({
  mode: 'pathsynch',
  useCustomBranding: true,
  agencyName: null,
  companyName: 'PathSynch Labs',
  logoUrl: null,
  logoStoragePath: null,
  logoMimeType: null,
  logoWidth: null,
  accentColor: '#0D9488',
  secondaryColor: null,
  footerText: 'Generated by PathSynch SynchIntro · Confidential',
  contactEmail: null,
  contactPhone: null,
  websiteUrl: null,
  showPoweredByPathSynch: true,
  canUseCustomLogo: false,
  canUseCustomColors: false,
});

// ---------------------------------------------------------------------------
// Compatibility hook for existing branding mutation callers. No result cache is retained.
function invalidateCache() {}

// ---------------------------------------------------------------------------
// Hex color normalization
// Accepts: #RGB → #RRGGBB, #RRGGBB pass-through
// Rejects: CSS vars, gradients, named colors, anything non-hex
// Returns: normalized 7-char hex string or null
// ---------------------------------------------------------------------------
const HEX_SHORT_RE = /^#([0-9a-f])([0-9a-f])([0-9a-f])$/i;
const HEX_FULL_RE  = /^#([0-9a-f]{6})$/i;

function _normalizeHex(value) {
  if (!value || typeof value !== 'string') return null;
  const v = value.trim();
  if (HEX_FULL_RE.test(v))  return v.toUpperCase().replace(/^#/, '#').slice(0, 7).toLowerCase().replace('#', '#');
  // keep it lowercase for consistency
  if (HEX_FULL_RE.test(v))  return v.toLowerCase();
  const short = v.match(HEX_SHORT_RE);
  if (short) return `#${short[1]}${short[1]}${short[2]}${short[2]}${short[3]}${short[3]}`.toLowerCase();
  return null;
}

// Small wrapper that returns the fallback when normalization fails
function _safeColor(value, fallback) {
  return _normalizeHex(value) || fallback || null;
}

// ---------------------------------------------------------------------------
// Entitlement defaults when no agencyEntitlements doc exists.
// Falls back to the user's subscription plan so existing paying users
// get the correct capability tier without requiring a seeded entitlements doc.
// ---------------------------------------------------------------------------
function _defaultEntitlements(planId) {
  return { planTier: planId || 'unresolved', canUseCustomLogo: null, canUseCustomColors: null, showPoweredByPathSynch: null };
}

// ---------------------------------------------------------------------------
// Determine capabilities from planTier
// (server-side enforcement layer — mirrors Firestore rules)
// ---------------------------------------------------------------------------
function _capabilitiesForTier(planTier) {
  switch ((planTier || 'starter').toLowerCase()) {
    case 'enterprise':
      return { canUseCustomLogo: true, canUseCustomColors: true, showPoweredByPathSynch: false };
    case 'scale':
      return { canUseCustomLogo: true, canUseCustomColors: true, showPoweredByPathSynch: false };
    case 'growth':
      return { canUseCustomLogo: false, canUseCustomColors: false, showPoweredByPathSynch: true };
    default: // starter
      return { canUseCustomLogo: false, canUseCustomColors: false, showPoweredByPathSynch: true };
  }
}

// ---------------------------------------------------------------------------
// Core resolver
// ---------------------------------------------------------------------------
/**
 * Resolve effective brand for a user.
 *
 * @param {string} userId - The calling user's UID
 * @param {object} [options]
 * @param {string} [options.workspaceId] - When present, resolve workspace OWNER's branding
 *   (reads entitlementOwnerUid from workspace doc). The calling member's personal branding
 *   is NOT used. Cache key is separated so a member's cached personal brand cannot leak
 *   into workspace context.
 * @returns {Promise<object>} resolvedBrand contract
 */
async function resolveBrand(userId, options = {}) {
  if (!userId) return { ...PATHSYNCH_DEFAULT_BRAND };

  const workspaceId = options.workspaceId || null;

  // Validate protected membership before resolving any workspace branding or capabilities.
  let brandOwnerId = userId;
  if (workspaceId) {
    try {
      brandOwnerId = (await require('./workspaceEntitlements').workspaceState(admin.firestore(), null, workspaceId, userId)).ownerUid;
    } catch (_) { return { ...PATHSYNCH_DEFAULT_BRAND }; }
  }
  // Authorization is always fresh: a prior paid response cannot survive a downgrade.

  let overrides = null;
  let entitlements = null;
  let verifiedPlan = null;

  try {
    const db = admin.firestore();

    if (workspaceId) {
      // 2a. WORKSPACE CONTEXT — read from server-only workspaceBranding/{workspaceId}
      // This doc is write:false in firestore.rules. Only the server handler can mutate it.
      // A direct client write to agencyBrandOverrides/{ownerUid} does NOT affect this doc.
      const [wsBrandSnap, entitlementsSnap, planId] = await Promise.all([
        db.collection('workspaceBranding').doc(workspaceId).get(),
        db.collection('agencyEntitlements').doc(brandOwnerId).get(),
        require('./workspaceEntitlements').effectivePlan(userId, workspaceId),
      ]);

      overrides    = wsBrandSnap.exists     ? wsBrandSnap.data()     : null;
      entitlements = entitlementsSnap.exists ? entitlementsSnap.data() : null;
      verifiedPlan = planId;

      // No fallback to agencyBrandOverrides in workspace context.
      // workspaceBranding/{wsId} is seeded at workspace creation from the owner's
      // agencyBrandOverrides. If the doc is absent, resolveBrand returns defaults.
      // This prevents a client write to agencyBrandOverrides from ever affecting
      // workspace-visible branding.
    } else {
      // 2b. SOLO CONTEXT — read from personal agencyBrandOverrides/{uid} (client-writable)
      const [overridesSnap, entitlementsSnap, planId] = await Promise.all([
        db.collection('agencyBrandOverrides').doc(brandOwnerId).get(),
        db.collection('agencyEntitlements').doc(brandOwnerId).get(),
        require('./workspaceEntitlements').effectivePlan(userId, workspaceId),
      ]);

      overrides    = overridesSnap.exists    ? overridesSnap.data()    : null;
      entitlements = entitlementsSnap.exists ? entitlementsSnap.data() : null;
      verifiedPlan = planId;
    }
  } catch (err) {
    console.error(`[BrandResolver] Firestore read failed for uid=${brandOwnerId}:`, err.message);
    // Fall through — all stay null → return default brand
  }

  // 3. No overrides at all → return default
  if (!overrides && !entitlements) {
    const brand = { ...PATHSYNCH_DEFAULT_BRAND };
    return brand;
  }

  // 3a. User disabled custom branding → return default (preserve their saved config, just don't apply it)
  if (overrides && overrides.useCustomBranding === false) {
    const brand = { ...PATHSYNCH_DEFAULT_BRAND, useCustomBranding: false };
    return brand;
  }

  // 4. Resolve entitlements (Firestore doc takes precedence; planTier drives capabilities)
  // Always derive a subscription-based fallback planTier — used when no entitlements doc
  // exists OR when the doc has a lower tier than the actual subscription (e.g. seeded as
  // 'starter' before the user upgraded).
  const subDefaults = _defaultEntitlements(verifiedPlan);
  const ent = entitlements || subDefaults;
  // Use whichever planTier is higher: entitlements doc or live subscription
  const TIER_RANK = { starter: 0, growth: 1, scale: 2, enterprise: 3 };
  const entTier = (ent.planTier || 'starter').toLowerCase();
  const subTier = subDefaults.planTier;
  const effectiveTier = (TIER_RANK[subTier] || 0) > (TIER_RANK[entTier] || 0) ? subTier : entTier;
  const caps = _capabilitiesForTier(effectiveTier);
  // Entitlements doc fields win over computed caps when explicitly set
  const canUseCustomLogo   = ent.canUseCustomLogo   != null ? !!ent.canUseCustomLogo   : caps.canUseCustomLogo;
  const canUseCustomColors = ent.canUseCustomColors != null ? !!ent.canUseCustomColors : caps.canUseCustomColors;
  const showPoweredBy      = ent.showPoweredByPathSynch != null ? !!ent.showPoweredByPathSynch : caps.showPoweredByPathSynch;

  // 5. Build resolvedBrand — capabilities gate which override fields are honoured
  const o = overrides || {};

  const accentColor = canUseCustomColors
    ? _safeColor(o.accentColor, PATHSYNCH_DEFAULT_BRAND.accentColor)
    : PATHSYNCH_DEFAULT_BRAND.accentColor;

  const secondaryColor = canUseCustomColors
    ? _normalizeHex(o.secondaryColor)
    : null;

  const logoUrl = canUseCustomLogo ? (o.logoUrl || null) : null;

  // companyName is allowed at all tiers (it's just a label — not a visual override)
  const companyName = (o.companyName && o.companyName.trim())
    ? o.companyName.trim()
    : PATHSYNCH_DEFAULT_BRAND.companyName;

  // footerText: growth tier appends " · Powered by PathSynch" regardless of what user set
  let footerText = (o.footerText && o.footerText.trim())
    ? o.footerText.trim()
    : `Generated by ${companyName} · Confidential`;

  if (showPoweredBy) {
    // Enforce "Powered by PathSynch" — append if not already present
    if (!footerText.toLowerCase().includes('powered by pathsynch')) {
      footerText = footerText + ' · Powered by PathSynch';
    }
  }

  // Determine mode
  let mode = 'pathsynch';
  if (!showPoweredBy && (logoUrl || accentColor !== PATHSYNCH_DEFAULT_BRAND.accentColor)) {
    mode = 'full';
  } else if (companyName !== PATHSYNCH_DEFAULT_BRAND.companyName || o.contactEmail || o.websiteUrl) {
    mode = 'partial';
  }

  const brand = {
    mode,
    useCustomBranding: overrides?.useCustomBranding !== false,
    agencyName:       (o.agencyName    && o.agencyName.trim())    || null,
    companyName,
    logoUrl,
    logoStoragePath:  canUseCustomLogo ? (o.logoStoragePath  || null) : null,
    logoMimeType:     canUseCustomLogo ? (o.logoMimeType     || null) : null,
    logoWidth:        canUseCustomLogo ? (o.logoWidth        || null) : null,
    accentColor,
    secondaryColor,
    footerText,
    contactEmail:     (o.contactEmail  && o.contactEmail.trim())  || null,
    contactPhone:     (o.contactPhone  && o.contactPhone.trim())  || null,
    websiteUrl:       (o.websiteUrl    && o.websiteUrl.trim())    || null,
    showPoweredByPathSynch: showPoweredBy,
    canUseCustomLogo,
    canUseCustomColors,
  };

  return brand;
}

module.exports = {
  resolvebrand: resolveBrand, // camelCase alias kept for consistency
  resolveBrand,
  invalidateCache,
  PATHSYNCH_DEFAULT_BRAND,
  // Exported for tests
  _normalizeHex,
  _capabilitiesForTier,
};
