'use strict';

/**
 * digestComposer.js — Pure email composition for SynchGov digests.
 *
 * No Firestore, no SendGrid. Returns { subject, htmlBody, textBody, ... }.
 */

// ── HTML Escaping ────────────────────────────────────────────────────────────

function _esc(str) {
    if (!str || typeof str !== 'string') return '';
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

function _stripCRLF(str) {
    if (!str) return '';
    return str.replace(/[\r\n]/g, ' ').trim();
}

// ── Score Badge ──────────────────────────────────────────────────────────────

function _scoreBadgeColor(label) {
    if (!label) return '#6B7280';
    const l = label.toLowerCase();
    if (l.includes('strong'))     return '#10B981';
    if (l.includes('possible'))   return '#3B82F6';
    if (l.includes('stretch'))    return '#F59E0B';
    if (l.includes('poor'))       return '#EF4444';
    if (l.includes('disqualified')) return '#6B7280';
    return '#6B7280';
}

// ── Compose ──────────────────────────────────────────────────────────────────

/**
 * Compose a digest email for a profile.
 *
 * @param {object} profile — GovProfile
 * @param {Array} opportunities — qualifying GovOpportunities, pre-filtered
 * @param {object} [options={}]
 * @param {boolean} [options.sendEmptyDigest=false]
 * @param {string} [options.frequency='daily']
 * @returns {{ subject, htmlBody, textBody, opportunityCount, opportunityIds }|null}
 */
function composeDigest(profile, opportunities, options = {}) {
    const { sendEmptyDigest = false, frequency = 'daily' } = options;
    const companyName = _esc(profile.profileName || 'Your Company');
    const dateStr = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

    // Sort by score desc
    const sorted = [...(opportunities || [])].sort((a, b) =>
        (b.fit?.score || 0) - (a.fit?.score || 0)
    );

    const count = sorted.length;

    if (count === 0) {
        if (!sendEmptyDigest) return null;

        const subject = _stripCRLF(`SynchGov ${frequency} digest: 0 opportunities for ${profile.profileName || 'your profile'}`);
        const htmlBody = _wrapHtml(`
            <h2 style="color:#1F2937;margin:0 0 16px">No new opportunities</h2>
            <p style="color:#6B7280;font-size:14px;">No new opportunities matched your criteria since the last digest. We'll keep watching.</p>
        `, companyName, dateStr);
        const textBody = `SynchGov ${frequency} digest for ${profile.profileName || 'your profile'}\n\nNo new opportunities matched your criteria since the last digest.`;

        return { subject, htmlBody, textBody, opportunityCount: 0, opportunityIds: [] };
    }

    const subject = _stripCRLF(`SynchGov ${frequency} digest: ${count} opportunit${count === 1 ? 'y' : 'ies'} for ${profile.profileName || 'your profile'}`);
    const opportunityIds = sorted.map(o => o._id || o.id || o.canonicalKey).filter(Boolean);

    // Build HTML rows
    const rows = sorted.map(opp => _renderOppRow(opp)).join('');
    const htmlBody = _wrapHtml(`
        <h2 style="color:#1F2937;margin:0 0 8px">${count} Opportunit${count === 1 ? 'y' : 'ies'} Found</h2>
        <p style="color:#6B7280;font-size:13px;margin:0 0 24px">${_esc(frequency)} digest for ${companyName}</p>
        ${rows}
    `, companyName, dateStr);

    // Plain text (generated separately — not HTML-stripped)
    const textRows = sorted.map(opp => _renderOppText(opp)).join('\n---\n');
    const textBody = `SynchGov ${frequency} digest for ${profile.profileName || 'your profile'}\n${count} opportunities found\n\n${textRows}\n\n---\nGenerated by SynchGov · ${dateStr}`;

    return { subject, htmlBody, textBody, opportunityCount: count, opportunityIds };
}

// ── HTML Renderers ───────────────────────────────────────────────────────────

function _renderOppRow(opp) {
    const fit       = opp.fit || {};
    const score     = fit.score || 0;
    const label     = _esc(fit.label || 'Unscored');
    const color     = _scoreBadgeColor(fit.label);
    const title     = _esc(opp.title || 'Untitled');
    const buyer     = _esc(opp.buyerName || '');
    const state     = _esc(opp.location?.state || '');
    const dueDate   = opp.dueDate ? new Date(opp.dueDate).toLocaleDateString('en-US') : 'No deadline';
    const source    = _esc(opp.primarySource || '');

    const reasons = (fit.reasonCodes || []).slice(0, 3).map(r =>
        `<span style="display:inline-block;background:#EFF6FF;color:#1E40AF;padding:2px 8px;border-radius:10px;font-size:11px;margin:2px">${_esc(r)}</span>`
    ).join('');

    const risks = (fit.riskCodes || []).map(r =>
        `<span style="display:inline-block;background:#FEF2F2;color:#DC2626;padding:2px 8px;border-radius:10px;font-size:11px;margin:2px">${_esc(r)}</span>`
    ).join('');

    const summary = _esc((opp.description || '').substring(0, 150));

    return `
    <div style="border:1px solid #E5E7EB;border-radius:8px;padding:16px;margin-bottom:12px">
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px">
            <span style="display:inline-block;background:${color};color:white;padding:2px 10px;border-radius:12px;font-size:12px;font-weight:600">${score} · ${label}</span>
            <span style="color:#6B7280;font-size:12px">${source}</span>
        </div>
        <h3 style="margin:0 0 4px;font-size:15px;color:#111827">${title}</h3>
        <p style="margin:0 0 8px;font-size:13px;color:#6B7280">${buyer}${state ? ' · ' + state : ''} · Due: ${_esc(dueDate)}</p>
        <div style="margin-bottom:8px">${reasons}${risks}</div>
        <p style="margin:0;font-size:13px;color:#4B5563">${summary}${summary.length >= 150 ? '…' : ''}</p>
    </div>`;
}

function _wrapHtml(bodyContent, companyName, dateStr) {
    return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;background:#f5f5f5">
<div style="max-width:600px;margin:0 auto;background:white">
    <div style="background:linear-gradient(135deg,#1E3A5F 0%,#2563EB 100%);padding:24px;text-align:center">
        <h1 style="color:white;margin:0;font-size:20px">SynchGov</h1>
        <p style="color:rgba(255,255,255,0.8);margin:4px 0 0;font-size:13px">Government Opportunity Intelligence</p>
    </div>
    <div style="padding:24px">
        ${bodyContent}
    </div>
    <div style="padding:16px 24px;background:#F9FAFB;border-top:1px solid #E5E7EB;text-align:center">
        <p style="margin:0;font-size:12px;color:#9CA3AF">Generated by SynchGov · ${_esc(dateStr)} · Manage settings in SynchIntro</p>
    </div>
</div></body></html>`;
}

// ── Plain Text Renderer ──────────────────────────────────────────────────────

function _renderOppText(opp) {
    const fit = opp.fit || {};
    const lines = [
        `[${fit.score || 0} · ${fit.label || 'Unscored'}] ${opp.title || 'Untitled'}`,
        `Buyer: ${opp.buyerName || 'Unknown'}${opp.location?.state ? ' · ' + opp.location.state : ''}`,
        `Due: ${opp.dueDate ? new Date(opp.dueDate).toLocaleDateString('en-US') : 'No deadline'}`,
        `Source: ${opp.primarySource || 'Unknown'}`,
    ];
    if (fit.reasonCodes?.length) lines.push(`Reasons: ${fit.reasonCodes.slice(0, 3).join(', ')}`);
    if (fit.riskCodes?.length) lines.push(`Risks: ${fit.riskCodes.join(', ')}`);
    if (opp.description) lines.push(`${opp.description.substring(0, 150)}`);
    return lines.join('\n');
}

module.exports = {
    composeDigest,
    // Exported for testing
    _esc,
    _stripCRLF,
    _scoreBadgeColor,
};
